#!/bin/sh

cat << EOF >> /etc/portage/make.conf/default
COMMON_FLAGS="${COMMON_FLAGS} -march=native"
VIDEO_CARDS="intel"
MAKEOPTS="-j5"
ACCEPT_LICENSE="* -@EULA"
ACCEPT_KEYWORDS="-~amd64"
FEATURES="parallel-install parallel-fetch getbinpkg binpkg-request-signature"
GRUB_PLATFORMS="efi-64"
USE="pulseaudio networkmanager wifi"
EOF
