#!/bin/sh
hname=gentoo
echo $hname > /etc/hostname
echo "127.0.1.1 $hname" >> /etc/hosts
ln -sf ../usr/share/zoneinfo/Asia/Tokyo /etc/localtime
echo '*** Set root password and add a user. ***'
echo '** passwd'
echo '** useradd -m -G user,wheel,audio -s $(which bash) USER'
