#!/bin/sh
echo 'gentoo' /etc/hostname
ln -sf ../usr/share/zoneinfo/Asia/Tokyo /etc/localtime
echo '*** Set root password and add a user. ***'
echo '** passwd'
echo '** useradd -m -G user,wheel,audio -s $(which bash) USER'
