#!/bin/sh

cat << EOF >> /etc/portage/package.use/list
*/* L10N: en ja
sys-kernel/installkernel grub dracut
app-admin/doas pam persist
net-misc/networkmanager tools wext wifi bluetooth iwd nftables policykit resolvconv syslog 
app-editors/vim vim-pager
app-editors/neovim nvim-pager
app-i18n/fcitx-configtool config-qt
app-i18n/mozc fcitx5 gui
EOF

getuto

emerge-webrsync
emerge --sync