#!/bin/sh

rm -rf /etc/portage/package.use
touch /etc/portage/package.use

cat << EOF >> /etc/portage/package.use
*/* L10N: en ja
app-admin/doas pam persist
app-editors/vim vim-pager
app-editors/neovim nvim-pager
dev-qt/qtwebengine jumbo-build
media-video/ffmpeg fdk
net-firewall/iptables nftables
net-libs/webkit-gtk jumbo-build
sys-kernel/installkernel grub dracut
EOF

emerge-webrsync && emerge --sync
emerge -auDN --getbinpkg @world
