#!/bin/sh

emerge-webrsync && emerge --sync
emerge -auDN --getbinpkg @world

emerge sys-kernel/linux-firmware
emerge sys-kernel/installkernel gentoo-kernel-bin
echo 'USE="${USE} dist-kernel"' >> /etc/portage/make.conf/default
