#!/bin/sh
emerge sudo neofetch

emerge app-admin/sysklogd
rc-update add sysklogd default

emerge sys-process/cronie
rc-update add cronie default

emerge net-misc/chrony
chronyd -q
rc-update add chronyd default
